finalproj/finalproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import weather.views as weather
import accounts.views as accounts
import blog.views as blog
import notice.views as notice
import quiz.views as quiz
import notifications.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", accounts.index),
    path('accounts/', include('allauth.urls')),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('', accounts.index, name='Index'),
    path('register/', accounts.sign_up, name='Register'),
    path('login/', accounts.sign_in, name='Login'),
    path('logout/', accounts.log_out, name='Logout'),
    path('profile/', accounts.profile, name='Profile'),
    path('profile/basic_info/', accounts.basic_info, name='Basic_info'),
    path('profile/account/', accounts.account, name='Account'),
    path('profile/dashboard/', accounts.dashboard, name='Dashboard'),
    path('profile/notifications/', accounts.notifications, name='Notifications'),
    path('profile/<int:id>', accounts.profile, name='Profile'),
    path('photo', accounts.upload_photo, name='Photo'),

    path('get_allsessions/', accounts.get_allsessions),
    # 忘記密碼頁面
    path('forgot_password/', accounts.forgot_password, name='forgot_password'),
    # 密碼重設確認頁面
    path('reset/confirm/<uidb64>/<token>/', accounts.password_reset_confirm, name='password_reset_confirm'),
    # 密碼重設完成頁面
    path('reset/complete/', accounts.password_reset_complete, name='password_reset_complete'),
    path('about/', accounts.about),
    
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice', notice.view_notifications, name='view_notifications'),
    
    # path('notice/', include('notice.urls', namespace='notice')),

    path('blog/', blog.index, name='blog_index'),
    path('blog/<str:category>/', blog.index, name='blog_index'),
    path('blog/<str:category>/<int:id>/',  blog.detail, name='blog_detail'),

    path('weather/', weather.weather),
    path('weather/town', weather.town, name='Town'),
    path('weather/radar', weather.radar),
    
    path('quiz/', quiz.question, name='quiz'),
    path('quiz/index/', quiz.quizindex),
    path('quiz/result/', quiz.quizresult),
    path('quiz/admin/', quiz.quiz_admin, name='quiz_admin'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalproj/quiz/models.py
from django.db import models
from accounts.models import UserProfile
from blog.models import BlogPost

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.category

class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.tag

class Question(models.Model):
    question = models.CharField(max_length=500, blank=False)
    # question_url = models.ImageField(upload_to='question_pics/',blank=True, null=True)
    question_url = models.URLField(blank=True, null=True)
    tag = models.ManyToManyField(Tag)
    choice1 = models.CharField(max_length=150)
    choice2 = models.CharField(max_length=150)
    choice3 = models.CharField(max_length=150)
    choice4 = models.CharField(max_length=150)
    TYPE_CHOICES = (
        ('Multiple Choice', 'Multiple Choice'),
        ('True or False', 'True or False'),
    )
    question_type = models.CharField(max_length=50,choices= TYPE_CHOICES)
    question_level = models.IntegerField(blank=False)
    correct_answer = models.CharField(max_length=50, choices=(
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
    ))
    # blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE, blank=True,null=True)
    detail_explanation = models.TextField(blank=True, null=True)
    # explanation_url = models.ImageField(upload_to='explanation_pics/',blank=True, null=True)
    explanation_url = models.URLField(blank=True, null=True)
    choice1_selected = models.IntegerField(default=0)
    choice2_selected = models.IntegerField(default=0)
    choice3_selected = models.IntegerField(default=0)
    choice4_selected = models.IntegerField(default=0)
    total_amount = models.IntegerField(default=0)
    correct_amount = models.IntegerField(default=0)
    correct_rate = models.FloatField(default=0)
    def __str__(self):
        return self.question
    
    def save(self, *args, **kwargs):
        if self.correct_answer == 'A':
            self.correct_amount = self.choice1_selected
        elif self.correct_answer == 'B':
            self.correct_amount = self.choice2_selected
        elif self.correct_answer == 'C':
            self.correct_amount = self.choice3_selected
        elif self.correct_answer == 'D':
            self.correct_amount = self.choice4_selected

        self.total_amount = self.choice1_selected + self.choice2_selected + self.choice3_selected + self.choice4_selected
        if self.total_amount > 0:
            self.correct_rate = round((self.correct_amount / self.total_amount), 4)*100
        super().save(*args, **kwargs)


class Quiz(models.Model):
    quiz_name = models.CharField(max_length=50)
    quiz_description = models.TextField(blank=True, null=True)
    quiz_questions = models.ManyToManyField(Question)
    question_amount = models.IntegerField(blank=False, default=10)
    question_score = models.IntegerField(blank=False, default=10)
    quiz_time = models.IntegerField(blank=False, default=300)
    def __str__(self):
        return self.quiz_name
    
    def save(self, *args, **kwargs):
        if self.question_amount > 0:
            self.question_score = 100 / self.question_amount
        super().save(*args, **kwargs)

class QuizResult(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.PROTECT)
    user = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    correct_amount = models.IntegerField(blank=False,default=0)
    score = models.IntegerField(blank=False)
    user_answer_time = models.IntegerField(blank=False, default=0)
    def __str__(self):
        return self.quiz.quiz_name + ' - ' + self.user.user.username + ' - ' + str(self.score)
    
class QuizResultDetail(models.Model):
    quiz_result = models.ForeignKey(QuizResult, on_delete=models.PROTECT)
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    user_answer = models.CharField(max_length=50)
    correct = models.BooleanField(default=False)
    def __str__(self):
        return self.quiz_result.quiz.quiz_name

finalproj/quiz/forms.py
from django import forms
from .models import Tag, Question, Quiz

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        widgets = {
            'tag': forms.TextInput(attrs={'class': 'form-control'}),
        }
        fields = '__all__'

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question', 'question_url', 'tag', 'choice1', 'choice2', 'choice3', 'choice4', 'question_type', 'question_level', 'correct_answer', 'detail_explanation', 'explanation_url']
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control'}),
            'question_url': forms.TextInput(attrs={'class': 'form-control'}),
            'tag': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'choice1': forms.TextInput(attrs={'class': 'form-control'}),
            'choice2': forms.TextInput(attrs={'class': 'form-control'}),
            'choice3': forms.TextInput(attrs={'class': 'form-control'}),
            'choice4': forms.TextInput(attrs={'class': 'form-control'}),
            'question_type': forms.Select(attrs={'class': 'form-control'}),
            'question_level': forms.NumberInput(attrs={'class': 'form-control'}),
            'correct_answer': forms.Select(attrs={'class': 'form-control'}),
            'detail_explanation': forms.Textarea(attrs={'class': 'form-control'}),
            'explanation_url': forms.TextInput(attrs={'class': 'form-control'}),
        }

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = '__all__'
        widgets = {
            'quiz_name': forms.TextInput(attrs={'class': 'form-control'}),
            'quiz_description': forms.Textarea(attrs={'class': 'form-control'}),
            'quiz_questions': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'question_amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'question_score': forms.NumberInput(attrs={'class': 'form-control'}),
            'quiz_time': forms.NumberInput(attrs={'class': 'form-control'}),
        }

finalproj/quiz/views.py
from django.shortcuts import render, redirect
from .models import Tag, Question, Quiz, QuizResult, QuizResultDetail
from .filters import TagFilter, QuestionFilter, QuizFilter, QuizResultFilter
from .forms import TagForm, QuestionForm, QuizForm
import random
import json

# Create your views here.
def question(request):
    quiz_id = request.GET.get('quizid')
    quiz = Quiz.objects.get(id=quiz_id)    
    questions = []
    for question in quiz.quiz_questions.all():
        questions.append(question)
    return render(request, 'quiz/quiz.html', locals())

def quizindex(request):
    return render(request, 'quiz/quizindex.html')

def quizresult(request):
    if request.method == 'POST':
        quiz_result = None
        quiz = None
        questions = []
        userAnswer = []
        correct_amount = 0
        user_answer_time = 0
        # 獲取表單數據
        for i, (key, value) in enumerate(request.POST.items()):
            # csrfmiddlewaretoken 為 CSRF 驗證所需的隱藏欄位，不需要處理
            if i == 0:
                pass
            # quiz_id
            elif i == 1:
                quiz_id = value
                # 保存 QuizResult 物件
                quiz = Quiz.objects.get(id=quiz_id)
                quiz_result = QuizResult.objects.create(
                    quiz=quiz,
                    user_id=request.user.id,
                    score=100,
                    user_answer_time=0,
                )
            elif i == 2:
                user_answer_time = value
                quiz_result.user_answer_time = user_answer_time
                quiz_result.save()
            else:
                question_dict = json.loads(value)  # 將 JSON 字串轉換為字典
                question_id = question_dict.get('id')  # 獲取題目 ID
                user_answer = question_dict.get('userAnswer')  # 獲取用戶的答案
                question = Question.objects.get(id=question_id)
                questions.append(question)
                userAnswer.append(user_answer)
                correct = False

                #答對
                if question.correct_answer == user_answer:
                    correct_amount += 1
                    correct = True
                
                if user_answer == 'A':
                    question.choice1_selected += 1
                elif user_answer == 'B':
                    question.choice2_selected += 1
                elif user_answer == 'C':
                    question.choice3_selected += 1
                elif user_answer == 'D':
                    question.choice4_selected += 1
                question.save()

                # 保存 QuizResultDetail 物件
                quiz_result_detail = QuizResultDetail.objects.create(
                    quiz_result=quiz_result,
                    question=question,
                    user_answer=user_answer,
                    correct=correct
                )
                # print(i, question_id, question_dict.get('userAnswer'))
        quiz_result.score = correct_amount * quiz.question_score
        quiz_result.correct_amount = correct_amount
        quiz_result.save() 

    return render(request, 'quiz/quizresult.html', locals())

def quiz_admin(request):
    questionForm = QuestionForm()
    quizForm = QuizForm()
    tagForm = TagForm()
    questions = Question.objects.all()
    selected_questions = []
    current_tab = 0
    if request.method == "POST":
        print(request.POST)
        if 'queryForm' in request.POST:
            questionFilter = QuestionFilter(request.POST, queryset=questions)
            if questionFilter.is_valid():
                print(request.POST.getlist('selected_questions'))
                if request.POST.get('selected_questions') == '' or request.POST.getlist('selected_questions')[0] == '[]':
                    selected_questions = []
                else:
                    selected_questions = list(map(int, request.POST.getlist('selected_questions')[0].replace('[', '').replace(']', '').split(',')))
                # print(selected_questions)
                # print(request.POST['quiz_name'])
                questions = questionFilter.qs
                # quizForm = QuizForm({'quiz_name': request.POST['quiz_name'], 'quiz_description': request.POST['quiz_description']})
                current_tab = 'three'
        elif 'tagForm' in request.POST:
            tagForm = TagForm(request.POST)
            if tagForm.is_valid():
                tag = tagForm.save()
                return redirect('quiz_admin')
            else:
                current_tab = 'one'
            
        elif 'questionForm' in request.POST:
            questionForm = QuestionForm(request.POST)
            if questionForm.is_valid():
                question = questionForm.save()
                question.tag.set(questionForm.cleaned_data.get('tag'))
                current_tab = 'two'
                return redirect('quiz_admin')
        elif 'quizForm' in request.POST:
            quizForm = QuizForm(request.POST)
            if quizForm.is_valid():
                quiz = quizForm.save()
                current_tab = 'three'
                return redirect('quiz_admin')
    else:
        # Get request, no form submission
        questionFilter = QuestionFilter(queryset=questions)
        
    # categories = tag.objects.all()
    # questions = Question.objects.all()
    # quizzes = Quiz.objects.all()
    # quiz_results = QuizResult.objects.all()

    # tagFilter = TagFilter(queryset=categories)
    # questionFilter = QuestionFilter(queryset=questions)
    # quizFilter = QuizFilter(queryset=quizzes)
    # quizResultFilter = QuizResultFilter(queryset=quiz_results)
    # if request.method == "POST":
    #     tagFilter = TagFilter(request.POST, queryset=categories)
    #     questionFilter = QuestionFilter(request.POST, queryset=questions)
    #     quizFilter = QuizFilter(request.POST, queryset=quizzes)
    #     quizResultFilter = QuizResultFilter(request.POST, queryset=quiz_results)
        
    return render(request, 'quiz/quizadmin.html', locals())

finalproj/templates/quiz/quizadmin.html
{% extends "base.html" %}
{% block title %}測驗管理頁面{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/quizadmin.css' %}">

<div class="container">
    <div class="tab-demo" >
        <!-- tab標籤列 -->
        <ul class="tab-title" style="list-style-type: none;justify-content:center;">
            <li>
                <a href="javascript:;" data-tablink="one">新增分類</a>
            </li>
            <li class="">
                <a href="javascript:;" data-tablink="two">新增問題</a>
            </li>
            <li>
                <a href="javascript:;" data-tablink="three">新增測驗</a>
            </li>
        </ul>
        <!-- tab內容 -->
        <div class="">
            <div id="one" class="tab-inner shadow-lg" style="border-radius: 10px;">
                <div style="margin: 15px;">
                    <h2 style="font-weight: bold; ">新增分類</h2>
                    <!-- 新增問題表單 -->
                    <form method="POST" >
                        {% csrf_token %}
                        {{ tagForm.as_p }}
                        <button type="submit" class="btn btn-success" name="tagForm" >新增</button>
                    </form>
                </div>
            </div>
            <div id="two" class="tab-inner shadow-lg" style="border-radius: 10px;">
                <div style="margin: 15px;">
                    <h2 style="font-weight: bold; ">新增問題</h2>
                    <!-- 新增問題表單 -->
                    <form method="POST" >
                        {% csrf_token %}
                        {{ questionForm.as_p }}
                        <!-- {{ questionForm.question }}
                        {{ questionForm.question_url }}
                        {{ questionForm.tag }}
                        {{ questionForm.choice1 }}
                        {{ questionForm.choice2 }}
                        {{ questionForm.choice3 }}
                        {{ questionForm.choice4 }}
                        {{ questionForm.question_type }}
                        {{ questionForm.correct_answer }}
                        {{ questionForm.detail_explanation }}
                        {{ questionForm.explanation_url }} -->
                        <button type="submit" class="btn btn-success" name="questionForm" >新增</button>
                    </form>
                </div>
            </div>
            <div id="three" class="tab-inner shadow-lg" style="border-radius: 10px;">
                <div style="margin: 15px;">
                    <h2 style="font-weight: bold; ">新增測驗</h2>
                    <form method="POST" id="quizForm">
                        {% csrf_token %}
                        {{ quizForm.as_p }}
                        <button type="submit" class="btn btn-success" name="quizForm">新增</button>
                    </form>
                    <hr>
                    <!-- 問題列表 -->
                    <h2 style="font-weight: bold; ">問題列表</h2> <span id="select-count">已選題數：</span>
                    <form method="POST" id="filterForm">
                        {% csrf_token %}
                        題目：{{ questionFilter.form.question }}
                        &emsp;
                        分類：{{ questionFilter.form.tag }}
                        &emsp;
                        題目類型：{{ questionFilter.form.question_type }}
                        &emsp;
                        <button type="submit" class="btn btn-primary" name="queryForm">查詢</button>
                        <input type="hidden" id="selectedQuestionsInput" name="selected_questions" value="{{ selected_questions }}" />
                    </form>
                    <br />
                    <table class="table">
                        <thead>
                            <th style="width: 55%;text-align: center;font-size: 16px;">題目</th>
                            <th style="width: 10%;text-align: center;font-size: 16px;">分類</th>
                            <th style="width: 10%;text-align: center;font-size: 16px;">題目類型</th>
                            <th style="width: 25%;text-align: center;font-size: 16px;"><button class="btn btn-primary" id="select-all-btn">全選</button>&nbsp;<button class="btn btn-danger" id="clear-all-btn">全刪</button></th>
                        </thead>
                        <tbody>
                            {% for question in questionFilter.qs %}
                            <tr>
                                <td>{{ question.question }}</td>
                                <td style="text-align: center;">
                                    {% for tag in question.tag.all %}
                                    {{ tag.tag }}
                                    {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{ question.get_question_type_display }}</td>
                                <td style="text-align: center;">
                                    <input type="checkbox" class="select-question form-check-input" name="selected_questions" value="{{ question.id }}" {% if question.id in selected_questions %}checked{% endif %}>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        tabCutover();
    });

    // function tabCutover1() {
    //     var tablink = $(".tab-title li.active").find("a").data("tablink");
    //     console.log(tablink);

    //     $('#' + tablink).show().siblings(".tab-inner").hide();

    //     $(".tab-title li").click(function () {
    //         $('#' + $(this).find("a").data("tablink")).show().siblings(".tab-inner").hide();
    //         $(this).addClass("active").siblings(".active").removeClass("active");
    //     });
    // }

    function tabCutover() {

        // $(".tab-title li.active").each(function () {
        //     var tablink = $(this).find("a").data("tablink");
        //     console.log(tablink);
        //     $('#' + tablink).show().siblings(".tab-inner").hide();
        // });
        var currentTab = "{{ current_tab }}"; // Replace "{{ current_tab }}" with the actual value passed from the view
        console.log(currentTab);
        // Show the default tab based on the current_tab parameter
        if (currentTab === "one") {
            $("#" + currentTab).show().siblings(".tab-inner").hide();
            $(".tab-title li").eq(0).addClass("active");
        } else if (currentTab === "two") {
            $("#" + currentTab).show().siblings(".tab-inner").hide();
            $(".tab-title li").eq(1).addClass("active");
        } else if (currentTab === "three") {
            $("#" + currentTab).show().siblings(".tab-inner").hide();
            $(".tab-title li").eq(2).addClass("active");
        }else{
            //預設顯示第二個頁籤
            $("#" + "two").show().siblings(".tab-inner").hide();
            $(".tab-title li").eq(1).addClass("active");
        }

        // Handle tab click event
        $(".tab-title li").click(function() {
            $("#" + $(this).find("a").data("tablink")).show().siblings(".tab-inner").hide();
            $(this).addClass("active").siblings(".active").removeClass("active");
        });
    }

</script>


<script>
// 在 DOM 加載完成後執行
document.addEventListener('DOMContentLoaded', function () {
    // 獲取選擇按鈕元素
    var selectButtons = document.querySelectorAll('.select-question');
    var selectElement = document.getElementById('id_quiz_questions');
    var hiddenInput = document.getElementById('selectedQuestionsInput');
    var selectedQuestions = new Set();
    console.log('hiddenInput',hiddenInput.value);
    if(hiddenInput.value != '[]'){
        selectedQuestions = new Set(hiddenInput.value.replace('[', '').replace(']', '').split(',').map(function (item) {
            return parseInt(item.trim()) == NaN ? null : parseInt(item.trim());
        }));
    }

    function updateSelectElement() {
        selectElement.querySelectorAll('option').forEach(function (option) {
            if (selectedQuestions.has(parseInt(option.value))) {
                option.selected = true;
            } else {
                option.selected = false;
            }
        });
    }

    updateSelectElement();

    // 更新勾選狀態
    selectButtons.forEach(function (button) {
        if (selectedQuestions.has(parseInt(button.value))) {
            button.checked = true;
        }

        button.addEventListener('click', function () {
            var questionId = parseInt(button.value);
            console.log('btn',button);
            if (button.checked) {
                selectedQuestions.add(questionId);
            } else {
                selectedQuestions.delete(questionId);
            }
            console.log('selectedQuestions',selectedQuestions);
            // 更新隱藏的輸入欄位值
            hiddenInput.value = Array.from(selectedQuestions).join(',');

            // 重置選中的選項
            selectElement.querySelectorAll('option').forEach(function (option) {
                option.selected = selectedQuestions.has(parseInt(option.value));
            });
            updateSelectedCount();
        });
    });

    // 監聽 quiz_questions 選擇框的變化事件
    selectElement.addEventListener('change', function () {
        
        selectedQuestions = new Set();

        // 清除所有選擇按鈕的勾選
        selectButtons.forEach(function (button) {
            button.checked = false;
        });

        // 更新勾選狀態
        selectElement.querySelectorAll('option').forEach(function (option) {
            if (option.selected) {
                selectedQuestions.add(parseInt(option.value));
            }
            var button = document.querySelector('.select-question[value="' + option.value + '"]');
            if (button) {
                button.checked = option.selected;
            }
        });
        console.log('selectedQuestions',selectedQuestions);
        // 更新隱藏的輸入欄位值
        hiddenInput.value = Array.from(selectedQuestions).join(',');
        updateSelectedCount();
    });

    // 更新已選擇題目數量
    function updateSelectedCount() {
        var selectedCountElement = document.getElementById('select-count');
        var questionAmountInput = document.getElementById('id_question_amount');
        var count = selectedQuestions.size;
        selectedCountElement.textContent = '已選題數：' + count;
        questionAmountInput.value = count;
    }

    updateSelectedCount();

    // 獲取全部選擇按鈕和全部清除按鈕的元素
    var selectAllBtn = document.getElementById('select-all-btn');
    var clearAllBtn = document.getElementById('clear-all-btn');

    // 全部選擇按鈕的點擊事件處理函式
    selectAllBtn.addEventListener('click', function () {
        // 遍歷篩選結果中的題目
        document.querySelectorAll('.select-question').forEach(function (button) {
            // 如果題目在篩選結果中，則勾選它並將其添加到已選擇題目集合中
            if (button.closest('tr')) {
                button.checked = true;
                selectedQuestions.add(parseInt(button.value));
                console.log('selectedQuestions',selectedQuestions);
            }
        });

        // 更新隱藏的輸入欄位值
        hiddenInput.value = Array.from(selectedQuestions).join(',');

        // 更新選擇框的選擇狀態
        updateSelectElement();

        // 更新已選擇題目數量
        updateSelectedCount();
    });

    // 全部清除按鈕的點擊事件處理函式
    clearAllBtn.addEventListener('click', function () {
        // 遍歷篩選結果中的題目
        document.querySelectorAll('.select-question').forEach(function (button) {
            // 如果題目在篩選結果中，則取消勾選它並從已選擇題目集合中刪除
            if (button.closest('tr')) {
                button.checked = false;
                selectedQuestions.delete(parseInt(button.value));
                console.log('selectedQuestions',selectedQuestions);
            }
        });

        // 更新隱藏的輸入欄位值
        hiddenInput.value = Array.from(selectedQuestions).join(',');

        // 更新選擇框的選擇狀態
        updateSelectElement();

        // 更新已選擇題目數量
        updateSelectedCount();
    });


    // 獲取表單元素
    var quizForm = document.getElementById('quizForm');
    var filterForm = document.getElementById('filterForm');

    // 監聽 filterForm 的提交事件
    filterForm.addEventListener('submit', function (event) {
        // event.preventDefault();
        // 建立 FormData 物件
        var formData = new FormData();
        formData.append('queryForm', '');
        var filterFormInputElements = filterForm.querySelectorAll('input, select, textarea');
        filterFormInputElements.forEach(function(input) {
            formData.append(input.name, input.value);
            console.log(input.name, input.value);
        });

        // 獲取 quizForm 的所有 input 元素
        var quizFormInputElements = quizForm.querySelectorAll('input, select, textarea');
        
        // 將 quizForm 的資料添加到 FormData 中
        quizFormInputElements.forEach(function(input) {
            formData.append(input.name, input.value);
            console.log(input.name, input.value);
        });

        // 提交 FormData 給後端處理
        fetch("{% url 'quiz_admin' %}", {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': document.getElementsByName("csrfmiddlewaretoken")[0].value
            }
        })
        .then(function (response) {
            // 在此處處理表單提交後的回應
        })
        .catch(function (error) {
            console.error('Error:', error);
        });
    });
});
</script>

{% endblock %}